Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> # for/while
>>> 
==================================================================== RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/while.py ====================================================================
땅 주인이 있나요? (예/아니요)아니요
통과
주사위롤 던져서 다음 땅으로 이동하세요
땅 주인이 있나요? (예/아니요)아니요
통과
주사위롤 던져서 다음 땅으로 이동하세요
땅 주인이 있나요? (예/아니요)예
통행료를 지불하시오
프로그램을 종료합니다.
>>> 예
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    예
NameError: name '예' is not defined
>>>  if 100>2
 
SyntaxError: unexpected indent
>>> if 100>1
SyntaxError: invalid syntax
>>> if 100>1:
	print(1)

	
1
>>> has_owner=True
>>> if has_owner==True:
	print('통행료를 지불하시오')

	
통행료를 지불하시오
>>> Type "help", "copyright", "credits" or "license()" for more information.
SyntaxError: invalid syntax
Type "help", "copyright", "credits" or "license()" for more information.
>>> 

>>> 

=
>>> 
==================================================================== RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/while.py ====================================================================
우주정거장에 도착했나요?(예/아니요)예
다시처음으로 돌아갑니다.
땅 주인이 있나요? (예/아니요)아니요
통과
주사위롤 던져서 다음 땅으로 이동하세요
우주정거장에 도착했나요?(예/아니요)아니요
땅 주인이 있나요? (예/아니요)예
통행료를 지불하시오
프로그램을 종료합니다.
>>> ;;;;;;;;;;;;;;;
SyntaxError: invalid syntax
>>> 
================================================================ RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/while,continue.py ===============================================================
우주정거장에 도착했나요?(예/아니요)예
다시처음으로 돌아갑니다.
땅 주인이 있나요? (예/아니요)아니요
통과
주사위롤 던져서 다음 땅으로 이동하세요
우주정거장에 도착했나요?(예/아니요)아니요
땅 주인이 있나요? (예/아니요)
================================================================ RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/while,continue.py ===============================================================
우주정거장에 도착했나요?(예/아니요)예
다시처음으로 돌아갑니다.
우주정거장에 도착했나요?(예/아니요)아니요
땅 주인이 있나요? (예/아니요)
통과
주사위롤 던져서 다음 땅으로 이동하세요
우주정거장에 도착했나요?(예/아니요)
땅 주인이 있나요? (예/아니요)

















==================================================================== RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/break.py ====================================================================
현재 가지고 있는 자산을 입력하세요;2
우주정거장에 도착했나요?(예/아니요)예
다시처음으로 돌아갑니다.
땅 주인이 있나요? (예/아니요)예
통행료를 지불하시오
프로그램을 종료합니다.
>>> 
==================================================================== RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/break.py ====================================================================
현재 가지고 있는 자산을 입력하세요;2
우주정거장에 도착했나요?(예/아니요)에
땅 주인이 있나요? (예/아니요)아니요
통과
주사위롤 던져서 다음 땅으로 이동하세요
현재 가지고 있는 자산을 입력하세요;2
우주정거장에 도착했나요?(예/아니요)예
다시처음으로 돌아갑니다.
현재 가지고 있는 자산을 입력하세요;
================================================================== RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py ==================================================================
제가 가장 좋아하는 색은 무엇일까요?blue
Traceback (most recent call last):
  File "C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py", line 4, in <module>
    if coloer=='red':
NameError: name 'coloer' is not defined
>>> red
Traceback (most recent call last):
  File "<pyshell#15>", line 1, in <module>
    red
NameError: name 'red' is not defined
>>> 
================================================================== RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py ==================================================================
제가 가장 좋아하는 색은 무엇일까요?red
Traceback (most recent call last):
  File "C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py", line 4, in <module>
    if coloer=='red':
NameError: name 'coloer' is not defined
>>> 
================================================================== RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py ==================================================================
제가 가장 좋아하는 색은 무엇일까요?blue
Traceback (most recent call last):
  File "C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py", line 3, in <module>
    if coloer=='red':
NameError: name 'coloer' is not defined
>>> 
================================================================== RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py ==================================================================
제가 가장 좋아하는 색은 무엇일까요?red
Traceback (most recent call last):
  File "C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py", line 3, in <module>
    if coloer=='red':
NameError: name 'coloer' is not defined
>>> 
================================================================== RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py ==================================================================
제가 가장 좋아하는 색은 무엇일까요?red
Traceback (most recent call last):
  File "C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py", line 4, in <module>
    if coloer=='red':
NameError: name 'coloer' is not defined
>>> 
================================================================== RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py ==================================================================
제가 가장 좋아하는 색은 무엇일까요?red
Traceback (most recent call last):
  File "C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py", line 3, in <module>
    if coloer=='red':
NameError: name 'coloer' is not defined
>>> 
================================================================== RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py ==================================================================
제가 가장 좋아하는 색은 무엇일까요?red
맞아요 빨간색 좋아합니다.
>>> 
================================================================== RESTART: C:/Users/ghkdh/Desktop/IDLE 프로그램/무한루프break.py ==================================================================
제가 가장 좋아하는 색은 무엇일까요?blue
그 색이 아니예요
제가 가장 좋아하는 색은 무엇일까요?blue
그 색이 아니예요
제가 가장 좋아하는 색은 무엇일까요?red
맞아요 빨간색 좋아합니다.
>>> 
==================================================================== RESTART: C:/Users/ghkdh/Desktop/for변수 in데이터(나열식).py ===================================================================
재
밌
는
 
파
이
썬
 
프
로
그
래
밍
>>> for n in range(10):
	print('저는 프로그래밍이 정말 좋아요')

	
저는 프로그래밍이 정말 좋아요
저는 프로그래밍이 정말 좋아요
저는 프로그래밍이 정말 좋아요
저는 프로그래밍이 정말 좋아요
저는 프로그래밍이 정말 좋아요
저는 프로그래밍이 정말 좋아요
저는 프로그래밍이 정말 좋아요
저는 프로그래밍이 정말 좋아요
저는 프로그래밍이 정말 좋아요
저는 프로그래밍이 정말 좋아요
>>> for n in '파이썬' range(10):
	
SyntaxError: invalid syntax
>>> for n in ;파이썬':
SyntaxError: invalid syntax
>>> for n in '파이썬':
	range(10)

	
range(0, 10)
range(0, 10)
range(0, 10)
>>> range(10)
range(0, 10)
>>> for n in ' 파이썬':
	range(10)
	print(n)

	
range(0, 10)
 
range(0, 10)
파
range(0, 10)
이
range(0, 10)
썬
>>> for n in rang(10):
	print(n,'번 반복문 수행')

	
Traceback (most recent call last):
  File "<pyshell#31>", line 1, in <module>
    for n in rang(10):
NameError: name 'rang' is not defined
>>> for n in range(10):
	print(n,'번 반복문 수행')

	
0 번 반복문 수행
1 번 반복문 수행
2 번 반복문 수행
3 번 반복문 수행
4 번 반복문 수행
5 번 반복문 수행
6 번 반복문 수행
7 번 반복문 수행
8 번 반복문 수행
9 번 반복문 수행
>>> for n in range(10):
	print(n)

	
0
1
2
3
4
5
6
7
8
9
>>> for n in range(10):
	if n%2==0:
		continue
	print(0)

	
0
0
0
0
0
>>> for n in range(10):
	if n%2==0:
		continue
	print(n)

	
1
3
5
7
9
>>> for n in range(10):
	if n==7:
		break
	if n%2==0:
		continue
	print(n)

	
1
3
5
>>> for x range(1,10):
	
SyntaxError: invalid syntax
>>> for x range(1,10):
	
SyntaxError: invalid syntax
>>> for x in range(1,10):
	for y in range(1,10):
		print(x,'x'y,'=',x*y)
		
SyntaxError: invalid syntax
>>>  for x in range(1,10):
	for y in range(1,10):
		print(x,'x',y,'=',x*y)
		
SyntaxError: unexpected indent
>>> for x in range(1,10):
	for y in range(1,10):
		print(x,'x'y,'=',x*y)
		
SyntaxError: invalid syntax
>>> for x in range(1,10):
	for y in range(1,10):
		print(x,'x',y,'=',x*y)

		
1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
>>> integers=(1,2,3,4,5)
>>> integers
(1, 2, 3, 4, 5)
>>> evens=2,4,6,8,10
>>> evens
(2, 4, 6, 8, 10)
>>> colors='red','yellow','blue'
>>> clors
Traceback (most recent call last):
  File "<pyshell#65>", line 1, in <module>
    clors
NameError: name 'clors' is not defined
>>> colors
('red', 'yellow', 'blue')
>>> book='파이썬',2019,300,'터닝포인트'
>>> book
('파이썬', 2019, 300, '터닝포인트')
>>> book-'파이썬',2019,300,'터닝포인트'
Traceback (most recent call last):
  File "<pyshell#69>", line 1, in <module>
    book-'파이썬',2019,300,'터닝포인트'
TypeError: unsupported operand type(s) for -: 'tuple' and 'str'
>>> book
('파이썬', 2019, 300, '터닝포인트')
>>> book[1]
2019
>>> book[3]
'터닝포인트'
>>> book[0]
'파이썬'
>>> book[-3]
2019
>>> len(book)
4
>>> count(book)
Traceback (most recent call last):
  File "<pyshell#76>", line 1, in <module>
    count(book)
NameError: name 'count' is not defined
>>> #문자열 길이 len()
>>> 
>>> book[4]
Traceback (most recent call last):
  File "<pyshell#79>", line 1, in <module>
    book[4]
IndexError: tuple index out of range
>>> book[0]
'파이썬'
>>> book[1]=2020
Traceback (most recent call last):
  File "<pyshell#81>", line 1, in <module>
    book[1]=2020
TypeError: 'tuple' object does not support item assignment
>>> good[1]=2020
Traceback (most recent call last):
  File "<pyshell#82>", line 1, in <module>
    good[1]=2020
NameError: name 'good' is not defined
>>> #튜플변경불가
>>> name,publish_year,pages,publisher=book
>>> name
'파이썬'
>>> publish_year
2019
>>> pages
300
>>> publisher
'터닝포인트'
>>> book
('파이썬', 2019, 300, '터닝포인트')
>>> scores=[85,92,98,71]
>>> scores
[85, 92, 98, 71]
>>> scores[3]
71
>>> scores[-1]
71
>>> len(scores)
4
>>> scores[4]
Traceback (most recent call last):
  File "<pyshell#95>", line 1, in <module>
    scores[4]
IndexError: list index out of range
>>> scores[2]=88
>>> scores
[85, 92, 88, 71]
>>> scores.append[90]
Traceback (most recent call last):
  File "<pyshell#98>", line 1, in <module>
    scores.append[90]
TypeError: 'builtin_function_or_method' object is not subscriptable
>>> scores.append(90)
>>> scores.remove(88)
>>> scores
[85, 92, 71, 90]
>>> scores(3,77)
Traceback (most recent call last):
  File "<pyshell#102>", line 1, in <module>
    scores(3,77)
TypeError: 'list' object is not callable
>>> scores.insert(3,77)
>>> scores
[85, 92, 71, 77, 90]
>>> scores.pop(1)
92
>>> scores
[85, 71, 77, 90]
>>> scores
[85, 71, 77, 90]
>>> scores.sort()
>>> scores
[71, 77, 85, 90]
>>> scores.sort(reverse=True)
>>> scores
[90, 85, 77, 71]
>>> scores.clear()
>>> scores=[85,92,88,71]
>>> a=(1,2,3)
>>> b=1,2,3.
>>> c=[1,2,3]
>>> b.append(3)
Traceback (most recent call last):
  File "<pyshell#117>", line 1, in <module>
    b.append(3)
AttributeError: 'tuple' object has no attribute 'append'
>>> a.append(3)
Traceback (most recent call last):
  File "<pyshell#118>", line 1, in <module>
    a.append(3)
AttributeError: 'tuple' object has no attribute 'append'
>>> c.append(7)
>>> c
[1, 2, 3, 7]
>>> 